version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: resumatch_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: resumatch2026
      MONGO_INITDB_DATABASE: resumatch_db
    volumes:
      - ./mongodb_data:/data/db
